<a href="https://colab.research.google.com/github/cibi-ruba-arasu/Headache-Classification/blob/main/Model_Training.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [111]:
import pandas as pd
import numpy as np
import joblib
import json
from sklearn.preprocessing import LabelEncoder

In [112]:
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, accuracy_score

In [44]:
dataset = pd.read_csv("/content/drive/MyDrive/headache1.csv")
dataset.head()

,Headache_Type,Pain_Type,Pain_Location,Pain_Duration,Onset_Speed,Nausea_Vomiting,Light_Sound_Sensitivity,Visual_Aura_or_Changes,Nasal_Congestion_Tearing,Recent_Head_Injury,Recent_Physical_Exertion,Medication_Overuse,Caffeine_Withdrawal,Menstruation_or_Hormones,High_Blood_Pressure,Recent_Lumbar_Puncture,Worsens_Upright
0,Exertion,Throbbing/Pulsing,Both sides,Minutes to Hours,Rapid (Under 1 min),No,No,No,No,No,Yes,No,No,No,No,No,No
1,Caffeine,Dull/Aching,All over,Minutes to Hours,Gradual,No,No,No,No,No,Yes,No,Yes,No,No,No,No
2,Cluster,Dull/Aching,Around one eye,Seconds,Rapid (Under 1 min),Yes,No,No,Yes,No,No,No,No,No,No,Yes,No
3,Exertion,Throbbing/Pulsing,Both sides,Minutes to Hours,Rapid (Under 1 min),No,No,No,No,No,Yes,Yes,No,No,No,No,No
4,Allergy or sinus,Throbbing/Pulsing,Sinus/Front,Minutes to Hours,Gradual,No,No,No,No,Yes,No,No,No,No,No,No,No

In [45]:
X = dataset.drop('Headache_Type', axis=1)
y = dataset['Headache_Type']

X_encoded = pd.get_dummies(X, drop_first=False)
X_encoded = X_encoded.astype(int)

le = LabelEncoder()

y_encoded = le.fit_transform(y)

target_mapping = dict(zip(le.classes_, le.transform(le.classes_)))

display(X_encoded.head())
display(y_encoded)
print(target_mapping)

,Pain_Type_Burning/Piercing,Pain_Type_Dull/Aching,Pain_Type_Severe,Pain_Type_Stabbing,Pain_Type_Throbbing/Pulsing,Pain_Location_All over,Pain_Location_Around one eye,Pain_Location_Back of head/Neck,Pain_Location_Both sides,Pain_Location_Moves around,...,Caffeine_Withdrawal_No,Caffeine_Withdrawal_Yes,Menstruation_or_Hormones_No,Menstruation_or_Hormones_Yes,High_Blood_Pressure_No,High_Blood_Pressure_Yes,Recent_Lumbar_Puncture_No,Recent_Lumbar_Puncture_Yes,Worsens_Upright_No,Worsens_Upright_Yes
0,0,0,0,0,1,0,0,0,1,0,...,1,0,1,0,1,0,1,0,1,0
1,0,1,0,0,0,1,0,0,0,0,...,0,1,1,0,1,0,1,0,1,0
2,0,1,0,0,0,0,1,0,0,0,...,1,0,1,0,1,0,0,1,1,0
3,0,0,0,0,1,0,0,0,1,0,...,1,0,1,0,1,0,1,0,1,0
4,0,0,0,0,1,0,0,0,0,0,...,1,0,1,0,1,0,1,0,1,0

array([ 3,  1,  2,  3,  0,  2,  3, 10,  0,  5,  6,  3,  3,  9, 11,  7, 12,
        5,  4, 10,  2, 13,  2,  1,  7, 13,  2,  7,  3,  7, 13,  9,  7,  9,
        2,  0,  2,  9,  1, 13,  2, 12,  1,  7, 10,  5,  1,  6, 12,  4,  5,
        7,  3,  9, 12,  9,  7,  3, 12,  7, 11,  4,  2,  1,  7,  2,  4,  5,
        6,  7,  8, 10,  4,  2,  7, 13,  1,  0, 12,  5, 10,  9, 13,  9,  5,
        9,  8, 10, 12,  4,  8,  9,  0,  2,  8,  7, 13,  4,  1,  3,  4,  3,
        9, 12, 12, 11,  3,  8,  9,  2,  1,  4, 10, 13,  1,  7,  1,  9, 11,
        8,  4,  2,  0,  5,  8, 13,  7, 13,  9,  8,  8,  3,  4,  5,  8,  0,
       10,  1, 10, 10,  8, 10,  6, 12,  3,  9, 13,  7, 13,  6,  1,  6, 13,
        7,  2,  4, 10,  9,  6,  3,  6,  5,  6, 12, 10,  7,  5, 10, 11, 10,
       10,  7,  0, 10, 11,  4,  8,  0,  6,  1,  9, 11,  1, 10,  0,  1, 12,
       11, 11,  1, 11, 11,  1,  7, 10,  4,  5,  3, 10, 12,  4,  1, 12, 11,
        1,  6, 13,  6, 12, 10,  7,  9,  4, 12,  1, 11,  7,  9, 11,  7,  6,
        6,  0,  6,  3,  5,  6,  1,  1, 11, 10,  3,  5,  7,  0,  8, 11,  2,
        7, 11, 10,  9,  9, 11, 10,  8,  6,  6,  2,  4,  3,  7, 12,  8,  8,
        2,  8,  1,  8,  6, 13,  7, 11, 12,  4,  7,  2,  7,  6, 12,  1, 10,
        4,  8,  1,  7,  1,  1,  6,  0, 10,  2,  8,  7, 13,  0,  3,  8,  6,
        8,  5, 10, 10,  2,  3,  9,  4,  4,  8,  1,  7,  2, 13,  9, 13,  4,
        2, 13, 12, 11, 11,  6, 11,  1,  1, 13,  8,  5,  7, 13, 10, 11, 13,
       13,  5,  7,  0,  2,  7,  3, 12,  7, 13,  3, 12,  3, 12,  3,  6,  1,
        7,  1,  7,  7, 11,  2,  6, 10,  3, 11, 11,  6, 13,  2,  1, 13,  1,
        6, 13,  8, 10,  9,  9, 10, 13, 10, 12,  4,  1, 10,  6,  7,  1,  6,
       10,  2,  0,  2,  1,  0, 11,  5,  8,  0,  7,  1, 11,  5,  4,  3,  8,
        3,  8, 12,  0,  3,  4,  9, 11,  1, 12,  0, 12,  2,  8,  5, 12, 10,
        5,  9, 10,  8,  3,  2,  0, 13,  0,  4,  4,  8, 11,  2,  1,  7, 10,
        4,  5,  1, 12,  1,  1,  6,  3,  9, 13,  6,  0,  6,  2,  9,  3,  1,
        4,  1,  4,  2,  6,  2,  8,  1,  3,  8,  2,  6, 13,  5,  6,  5, 11,
        2,  3,  9, 11,  0, 12,  8, 10,  7,  5,  6, 11,  6,  0,  1,  9,  8,
       10,  7, 11, 13,  4,  3,  4, 11, 10,  9,  0, 11,  0, 12,  0, 11, 12,
       11,  9,  8, 10, 12,  8,  5])

{'Allergy or sinus': np.int64(0), 'Caffeine': np.int64(1), 'Cluster': np.int64(2), 'Exertion': np.int64(3), 'Hemicrania continua': np.int64(4), 'Hormone': np.int64(5), 'Hypertension': np.int64(6), 'Ice pick': np.int64(7), 'Migraine': np.int64(8), 'Post-traumatic': np.int64(9), 'Rebound': np.int64(10), 'Spinal': np.int64(11), 'Tension': np.int64(12), 'Thunderclap': np.int64(13)}

In [103]:
X_train, X_test, y_train, y_test = train_test_split(
    X_encoded, y_encoded, test_size=0.2, random_state=42, stratify=y_encoded
)

rf_model = RandomForestClassifier(n_estimators=1000, random_state=42)

rf_model.fit(X_train, y_train)

y_pred = rf_model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print("Overall Model Accuracy:", accuracy)

print("Detailed Classification Report:")
print(classification_report(y_test, y_pred, target_names=le.classes_))

Overall Model Accuracy: 0.86
Detailed Classification Report:
                     precision    recall  f1-score   support

   Allergy or sinus       0.86      1.00      0.92         6
           Caffeine       0.75      0.90      0.82        10
            Cluster       1.00      0.86      0.92         7
           Exertion       0.86      0.86      0.86         7
Hemicrania continua       1.00      0.83      0.91         6
            Hormone       0.75      0.60      0.67         5
       Hypertension       0.70      1.00      0.82         7
           Ice pick       1.00      1.00      1.00         9
           Migraine       0.67      0.86      0.75         7
     Post-traumatic       1.00      1.00      1.00         7
            Rebound       0.71      0.62      0.67         8
             Spinal       1.00      1.00      1.00         8
            Tension       1.00      0.57      0.73         7
        Thunderclap       1.00      0.83      0.91         6

           accuracy                           0.86       100
          macro avg       0.88      0.85      0.86       100
       weighted avg       0.88      0.86      0.86       100

In [104]:
rf_base = RandomForestClassifier(random_state=42)

param_grid = {
    'n_estimators': [50, 100, 200, 300],
    'max_depth': [None, 5, 10, 15, 20],
    'max_features': ['sqrt', 'log2', None]
}

grid_search = GridSearchCV(
    estimator=rf_base,
    param_grid=param_grid,
    cv=5,
    n_jobs=-1,
    verbose=2
)

print("Dont interrupt cell runtime...")
grid_search.fit(X_train, y_train)

#print("Accuracy score(mean test score) of All Combinations:")
#means = grid_search.cv_results_['mean_test_score']
#params = grid_search.cv_results_['params']

#for mean_score, parameters in zip(means, params):
    #print("Accuracy:",mean_score, "Parameters:", parameters)

print("Display Best set of parameter combination")
print("Best Parameter:",grid_search.best_params_)
print("Best Cross-Validation Accuracy:",grid_search.best_score_)

best_rf_model = grid_search.best_estimator_
tuned_acc = best_rf_model.score(X_test, y_test)

print("Final Tuned Test Accuracy:",tuned_acc)

Dont interrupt cell runtime...
Fitting 5 folds for each of 60 candidates, totalling 300 fits
Display Best set of parameter combination
Best Parameter: {'max_depth': 10, 'max_features': 'log2', 'n_estimators': 200}
Best Cross-Validation Accuracy: 0.8475000000000001
Final Tuned Test Accuracy: 0.86

change values of the next cell for custom prediction using the best possible model

In [109]:
user_symptoms = {
    'Pain_Type': ['Dull/Aching'],
    # Options: 'Dull/Aching', 'Burning/Piercing', 'Throbbing/Pulsing', 'Stabbing', 'Severe'

    'Pain_Location': ['One side'],
    # Options: 'All over', 'Back of head/Neck', 'Both sides', 'Around one eye', 'One side', 'Moves around', 'Sinus/Front'

    'Pain_Duration': ['4 to 72 hours'],
    # Options: 'Minutes to Hours', '4 to 72 hours', 'Continuous (>3 months)', 'Seconds'

    'Onset_Speed': ['Gradual'],
    # Options: 'Gradual', 'Rapid (Under 1 min)'

    'Nausea_Vomiting': ['Yes'],
    # Options: 'No', 'Yes'

    'Light_Sound_Sensitivity': ['Yes'],
    # Options: 'No', 'Yes'

    'Visual_Aura_or_Changes': ['No'],
    # Options: 'No', 'Yes'

    'Nasal_Congestion_Tearing': ['No'],
    # Options: 'No', 'Yes'

    'Recent_Head_Injury': ['No'],
    # Options: 'No', 'Yes'

    'Recent_Physical_Exertion': ['No'],
    # Options: 'No', 'Yes'

    'Medication_Overuse': ['No'],
    # Options: 'No', 'Yes'

    'Caffeine_Withdrawal': ['No'],
    # Options: 'No', 'Yes'

    'Menstruation_or_Hormones': ['No'],
    # Options: 'No', 'Yes'

    'High_Blood_Pressure': ['No'],
    # Options: 'No', 'Yes'

    'Recent_Lumbar_Puncture': ['No'],
    # Options: 'No', 'Yes'

    'Worsens_Upright': ['Yes']
    # Options: 'No', 'Yes'
}

print("possible Outcomes:")
poss = list(set(dataset["Headache_Type"]))
for i in range(0, len(poss)):
  print(poss[i])

possible Outcomes:
Post-traumatic
Rebound
Hypertension
Migraine
Thunderclap
Exertion
Tension
Cluster
Ice pick
Hemicrania continua
Hormone
Allergy or sinus
Spinal
Caffeine

In [110]:
user_df = pd.DataFrame(user_symptoms)

user_encoded = pd.get_dummies(user_df)
user_encoded = user_encoded.reindex(columns=X_train.columns, fill_value=0)
user_encoded = user_encoded.astype(int)

predicted_class_int = best_rf_model.predict(user_encoded)
predicted_headache_name = le.inverse_transform(predicted_class_int)

print(f"Based on the symptoms, the predicted headache is: {predicted_headache_name[0]}")

Based on the symptoms, the predicted headache is: Migraine

In [113]:
joblib.dump(best_rf_model, 'best_rf_headache_model.pkl')

joblib.dump(le, 'label_encoder.pkl')

model_columns = list(X_train.columns)
with open('model_columns.json', 'w') as f:
    json.dump(model_columns, f)